# InteroSight Robust Training Configuration

# Model Configuration
model:
  base_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  quantization: "4bit"
  lora:
    r: 8
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj"]
    lora_dropout: 0.05
    bias: "none"
    task_type: "CAUSAL_LM"

# Data Configuration - Using Robust Dataset
data:
  use_robust_data: true
  robust_data_path: "interosight/data/robust_training_data.jsonl"
  synthetic_data_path: "interosight/data/synthetic/mi_training_data.jsonl"  # Fallback
  max_length: 512
  train_split: 0.9
  seed: 42

# Training Configuration - Adjusted for Robust Data
training:
  num_epochs: 5  # More epochs for larger dataset
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 1.5e-4  # Slightly lower for stability
  warmup_steps: 200  # More warmup for larger dataset
  logging_steps: 25
  save_steps: 1000
  eval_steps: 1000
  fp16: true
  dataloader_pin_memory: false

# Output Configuration
output:
  output_dir: "interosight/logs/training_robust"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

# Generation Configuration (for inference)
generation:
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  do_sample: true 