# InteroSight Training Configuration

# Model Configuration
model:
  base_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  quantization: "4bit"
  lora:
    r: 8
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj"]
    lora_dropout: 0.05
    bias: "none"
    task_type: "CAUSAL_LM"

# Data Configuration
data:
  train_path: "interosight/data/synthetic/mi_training_data.jsonl"
  max_length: 512
  train_split: 0.9
  seed: 42

# Training Configuration
training:
  num_epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  warmup_steps: 100
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  fp16: true
  dataloader_pin_memory: false

# Output Configuration
output:
  output_dir: "interosight/logs/training"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

# Generation Configuration (for inference)
generation:
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  do_sample: true 